version: '3.8'

services:
  trainchecker:
    image: joegrice/trainchecker:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - TZ=Europe/London
    restart: unless-stopped